### ISSUE TITLE
All companions at Level 1?

### ISSUE THREAD

**Issue by admiralzeech** [alterasc/LevelUpPlanCustomizer#4]
Hi, thanks for the mod!

Just a question, is this mod able to override companion's initial builds, such that every companion only has Level 1? (And thus you are free to choose all the other levels in-game.)

Or are we forced to use the mod to define their initial builds up until the level they are introduced at?

**Comment by alterasc** [comment]
You can specify their builds from level 1, but level that companions join you at is defined in another place and not configurable with this mod.
